### ISSUE TITLE
i don't know how to use it in editor ?

### ISSUE THREAD

**Issue by abdelrahmanbadr** [lanly-dev/VSCode-VoiceCommands#1]

**Comment by lanly-dev** [comment]
You can start the program by typing "voice commands" in the VSCode's Command Palette

`Ctrl+Shift+P, F1` Show Command Palette 

https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf

**Comment by abdelrahmanbadr** [comment]
Thanks
