### ISSUE TITLE
New commands are not working

### ISSUE THREAD

**Issue by jbharatrhodes** [lanly-dev/VSCode-VoiceCommands#2]
Hi Mate,
I tried to add new commands (New file , Open file etc) but I am unable to do that. Do I need to work on the Grammar file? 
Thank you

**Comment by lanly-dev** [comment]
Hello there,
Yes, you are correct. This extension actually creates a child process to run executable file in the background and get the results via `stdout.on()`.
You could look into `/backend/` there are 2 projects(C# and Java) to build those 2 standalone executable files.
Note that, for  the Java one you have to generate .dic and .lm from this online tool [http://www.speech.cs.cmu.edu/tools/lmtool-new.html](http://www.speech.cs.cmu.edu/tools/lmtool-new.html) by inputting the `corpus.txt`.
